### ISSUE TITLE
`Modio.auth().request_code(email)` not sending email

### ISSUE THREAD

**Issue by valentinegb** [nickelc/modio-rs#5]
Not really much I can say unfortunately, I have this code:

```rust
let modio = Modio::new(Credentials::new(env!("MODIO_API_KEY")))?;

modio.auth().request_code("valentinegb@icloud.com").await?;
```

but I'm not receiving any emails. Not sure if I'm doing something wrong, if this is a bug with the wrapper, or if it's a bug with the SDK- please offer some assistance.

**Comment by nickelc** [comment]
I tried to log in with my cli tools [nickelc/modiom](https://github.com/nickelc/modiom). I've just received an email from the test-env with a security code.

```
modiom login --test-env
```

**Comment by valentinegb** [comment]
I installed modiom and ran the same command, it said `Authentication code request was successful.` but I still didn't get an email.

**Comment by nickelc** [comment]
hmmm, if there is no email in the spam folder then maybe the email bounced.
I would contact the mod.io team.
